export const navItems = [
  { id: "home", label: "首页总览", icon: "layout" },
  { id: "analysis", label: "剧本分析", icon: "scan" },
  { id: "cases", label: "案例库", icon: "archive" },
  { id: "assets", label: "模式资产", icon: "layers" },
  { id: "learning", label: "案例学习 / 爆款模式", icon: "spark" },
  { id: "skills", label: "Skill 进化", icon: "spark" },
  { id: "decision", label: "创作决策", icon: "compass" },
  { id: "outline", label: "细纲生产", icon: "list" },
  { id: "draft", label: "成稿中心", icon: "pen" },
  { id: "audit", label: "审计修复", icon: "shield" },
  { id: "feedback", label: "反馈回流", icon: "loop" },
  { id: "settings", label: "系统设置", icon: "settings" }
];

export const taskLabels = {
  analyzeScript: "剧本结构分析",
  analyzeScriptChunk: "剧本切块分析",
  analyzeEpisodeChunk: "分集 Chunk 分析",
  aggregateScriptAnalysis: "全剧结构聚合",
  mergeEvidenceLedAnalysis: "证据分析合并",
  extractStoryBlueprint: "提炼剧本骨架 Blueprint",
  analyzeViralMechanism: "分析爆款机制",
  extractPatternCards: "提炼 Pattern Cards",
  buildSkillAssetsFromPatterns: "Pattern 生成 Skill 资产",
  applyPatternsToNewIdea: "Pattern 迁移到新创意",
  auditPatternTransfer: "迁移结果审计",
  extractPatterns: "模式提取",
  classifyCase: "案例分类",
  generateSkillSuggestion: "Skill 优化建议",
  testSkillVersion: "Skill 回归测试",
  evaluateIdea: "创意评估",
  generateDirections: "方向方案生成",
  generateThemeCandidates: "主题与情绪生成",
  generateMainlineReversals: "主线大反差生成",
  generateEndingCandidates: "结局方案生成",
  generateMajorNodes: "大节点生成",
  generateMacroOutline: "宏观结构生成",
  generateCharacterCore: "人物核心生成",
  generateGoldfinger: "金手指生成",
  generateStoryEngine: "故事发动机生成",
  generateMaterialPools: "素材池生成",
  generateStageOutline: "阶段大纲生成",
  generateEpisodeOutline: "分集细纲生成",
  auditOutline: "细纲审计",
  repairSection: "局部修复",
  generateDraft: "成稿生成",
  auditDraft: "成稿审计",
  jsonRepair: "JSON 修复",
  schemaRepairAnalyzeScript: "剧本分析结构修复",
  schemaRepairAnalyzeEpisodeChunk: "分集结构修复",
  summarizeLongText: "长文本总结",
  classifyTags: "分类与标签"
};

export const statusLabels = {
  idea: "创意阶段",
  decision: "决策阶段",
  outline: "细纲阶段",
  draft: "成稿阶段",
  audit: "审计阶段",
  frozen: "已冻结"
};

export const analysisTabs = [
  ["overview", "总览"],
  ["evidence", "证据账本"],
  ["beats", "Beat 账本"],
  ["hook", "开头"],
  ["emotion", "情绪需求"],
  ["theme", "主题"],
  ["characters", "人物"],
  ["goldfinger", "金手指"],
  ["mainline", "主线骨架"],
  ["reversal", "大反差"],
  ["ending", "结局"],
  ["episodes", "分集功能"],
  ["patterns", "可复用模式"]
];

export const assetCategories = [
  ["audienceNeeds", "情绪需求"],
  ["hooks", "开头钩子"],
  ["mainlineSkeletons", "主线骨架"],
  ["mainlineReversals", "主线大反差"],
  ["goldfingers", "金手指"],
  ["relationships", "人物关系"],
  ["rhythms", "分集节奏"],
  ["endings", "结局兑现"]
];

export const lockItems = [
  ["direction", "创意方向"],
  ["theme", "主题与情绪"],
  ["reversal", "主线大反差"],
  ["ending", "结局"],
  ["majorNodes", "大节点"],
  ["characterCore", "人物核心"],
  ["goldfinger", "金手指"],
  ["storyEngine", "故事发动机"],
  ["stageOutline", "阶段大纲"],
  ["episodeOutline", "分集细纲"],
  ["draft", "成稿"]
];

export const hookTypes = [
  "羞辱开局",
  "危机开局",
  "死亡/重生开局",
  "退婚/背叛开局",
  "身份错位开局",
  "强者伪装弱者开局",
  "系统觉醒开局",
  "金手指暴露开局",
  "悬疑提问开局",
  "极致反差开局",
  "高压选择开局",
  "关系撕裂开局",
  "命运倒计时开局"
];

export const audienceNeedTypes = [
  "尊严修复",
  "公平清算",
  "极致偏爱",
  "身份跃迁",
  "控制感补偿",
  "自由幻想",
  "被爱与被拯救",
  "认知优越感",
  "复仇释放",
  "秩序重建",
  "命运反抗",
  "被误解后的证明",
  "被抛弃后的反击",
  "被压迫后的翻身"
];

export const fieldLabels = {
  id: "ID",
  title: "标题",
  name: "名称",
  description: "说明",
  logline: "一句话梗概",
  summary: "摘要",
  openingSummary: "开头概述",
  hookTypes: "钩子类型",
  firstSceneFunction: "首场功能",
  firstEpisodeFunction: "首集功能",
  conflictIntroduced: "引入冲突",
  suspenseIntroduced: "引入悬念",
  contrastIntroduced: "引入反差",
  emotionalPressure: "情绪压力",
  viewerQuestion: "观众追问",
  whyContinueWatching: "继续观看理由",
  hookStrengthScore: "钩子强度",
  primaryNeeds: "主要情绪需求",
  secondaryNeeds: "次要情绪需求",
  emotionalReleaseMechanism: "情绪释放机制",
  audiencePainPoint: "观众现实痛点",
  fantasyCompensation: "幻想补偿",
  satisfactionPath: "满足路径",
  emotionalNeedScore: "情绪需求强度",
  themeStatement: "主题句",
  deepTheme: "深层主题",
  antiThemeForce: "反主题力量",
  themeCarrierCharacters: "主题承载人物",
  themeConflict: "主题冲突",
  howThemeIsExpressed: "主题表达方式",
  themePayoff: "主题兑现",
  themeStrengthScore: "主题承载强度",
  emotionalPromise: "情绪承诺",
  emotionalPayoff: "情绪兑现",
  coreConflict: "核心冲突",
  mainAppeal: "主要看点",
  audienceNeeds: "观众情绪需求",
  risks: "风险",
  strengths: "优势",
  weaknesses: "弱点",
  suggestedRepairs: "修复建议",
  hasGoldfinger: "是否有金手指",
  type: "类型",
  visibleFunction: "显性功能",
  hiddenNature: "隐藏本质",
  rules: "规则",
  limits: "限制",
  costs: "代价",
  upgradePath: "升级路径",
  coolUses: "爽点用法",
  misuseRisks: "误用风险",
  relationshipToCharacterArc: "人物弧光关系",
  relationshipToMainlineReversal: "主线大反差关系",
  goldfingerStrengthScore: "金手指强度",
  obstacleTypes: "阻碍类型",
  obstacleEscalation: "阻碍升级",
  antagonistSystem: "反派系统",
  whyCannotBeSolvedAtOnce: "为何不能一次解决",
  pressureMechanism: "压力机制",
  obstacleStrengthScore: "阻碍强度",
  recommendation: "建议",
  stageNo: "阶段序号",
  episodeRange: "集数范围",
  stageGoal: "阶段目标",
  mainConflict: "主要冲突",
  majorTurningPoint: "关键转折",
  protagonistStartPoint: "主角起点",
  protagonistGoal: "主角目标",
  drivingQuestion: "驱动问题",
  stageStructure: "阶段结构",
  escalationLogic: "升级逻辑",
  midpointChange: "中点变化",
  finalConflict: "终局冲突",
  mainlineStrengthScore: "主线强度",
  hasMainlineReversal: "是否有主线大反差",
  surfaceStory: "表层故事",
  deepTruth: "深层真相",
  reversalTypes: "反差类型",
  revealTiming: "揭示时机",
  foreshadowingBeforeReveal: "揭示前伏笔",
  impactAfterReveal: "揭示后影响",
  characterImpact: "人物影响",
  themeConnection: "主题关联",
  reversalStrengthScore: "大反差强度",
  endingSummary: "结局概述",
  protagonistFinalState: "主角最终状态",
  antagonistFinalState: "反派最终状态",
  relationshipFinalState: "关系最终状态",
  worldFinalState: "世界最终状态",
  promisedEmotionReturned: "是否兑现情绪承诺",
  unresolvedIssues: "未解决问题",
  endingStrengthScore: "结局强度",
  openingHook: "开头钩子",
  episodeGoal: "本集目标",
  conflict: "核心冲突",
  mainConflict: "核心冲突",
  keyEvent: "关键事件",
  goldfingerUse: "金手指使用",
  coolMoment: "爽点",
  emotionalBeat: "情绪节拍",
  plotTwist: "本集反转",
  cliffhanger: "结尾悬念",
  characterFunction: "人物功能",
  audienceNeedServed: "观众情绪",
  themeFunction: "主题功能",
  relationshipChange: "关系变化",
  informationGain: "信息增量",
  foreshadowingUsed: "伏笔回收",
  foreshadowingPlanted: "伏笔埋设",
  episodeNo: "集数",
  episodeFunctionType: "本集功能类型",
  weaknessNotes: "弱点提示",
  score: "评分",
  continuityNotes: "连续性说明",
  riskNotes: "风险提示",
  antagonistGoal: "反派目标",
  centralConflict: "中心冲突",
  whyCannotStop: "为何不能停下",
  whyGoldfingerCannotSolveEverything: "金手指为何不能解决一切",
  stageGoals: "阶段目标",
  obstacleSystem: "阻碍系统",
  stakesEscalation: "风险升级",
  postReversalGoalChange: "反差后的目标变化",
  surfaceDesire: "表层欲望",
  innerLack: "真正缺失",
  misbelief: "最大误判",
  fear: "恐惧",
  wound: "伤口",
  temptation: "诱惑",
  mask: "面具",
  motivation: "动机",
  relationshipToTheme: "主题关系",
  relationshipToReversal: "大反差关系",
  turningPoints: "转折点",
  finalChoice: "最终选择",
  arcSummary: "人物弧光",
  archetype: "人物原型",
  role: "角色功能",
  conflictWithProtagonist: "与主角的冲突",
  relationshipEdges: "人物关系边",
  characterSystemSummary: "人物系统总结",
  characterStrengthScore: "人物强度",
  early: "前期伏笔",
  middle: "中段伏笔",
  late: "后期伏笔",
  firstReveal: "第一次揭示",
  midReveal: "中段揭示",
  finalReveal: "最终揭示",
  before: "修改前",
  after: "修改后",
  changeSummary: "修改摘要",
  impactScope: "影响范围",
  source: "来源",
  category: "分类",
  skillType: "Skill 类型",
  genreScope: "适用题材",
  audienceNeedScope: "适用观众情绪",
  platformScope: "适用平台/形态",
  taskScope: "适用任务",
  priority: "优先级",
  promptAdditions: "Prompt 补充",
  positiveExamples: "正例",
  negativeExamples: "反例",
  evaluationCriteria: "评估标准",
  riskWarnings: "风险提示",
  modelPreference: "模型偏好",
  format: "内容形态",
  genre: "题材",
  subGenre: "细分题材",
  episodeCount: "集数",
  estimatedLength: "长度估计",
  targetAudience: "目标用户",
  platformFit: "平台适配",
  coreAppeal: "核心看点",
  commercialPositioning: "商业定位",
  classificationTags: "分类标签",
  qualityNotes: "质量备注",
  analystNotes: "分析说明",
  confidence: "结构信心",
  coverage: "输入完整度",
  caseScope: "入库类型",
  inputType: "输入类型",
  detectedEpisodeCount: "检测到集数",
  userEpisodeCount: "用户填写集数",
  estimatedCoverageRatio: "覆盖比例",
  allowedCaseScope: "可入库类型",
  evidenceIds: "证据 ID",
  evidenceBeatIds: "关联 Beat",
  inferenceLevel: "判断层级",
  needsReview: "需要复核",
  sourceText: "原文片段",
  beatSummary: "Beat 摘要",
  suspenseQuestion: "悬念问题",
  structureFunction: "结构功能",
  reusableValue: "可复用价值",
  relatedModules: "关联模块",
  sourceEvidenceIds: "来源证据",
  sourceBeatIds: "来源 Beat",
  structureSteps: "结构步骤",
  variableSlots: "变量槽",
  emotionalMechanism: "情绪机制",
  plotFunction: "剧情功能",
  characterFunction: "人物功能",
  antiPatterns: "反模式",
  reusePrompt: "复用 Prompt",
  sourceMeta: "来源与修复信息",
  userGenreNote: "用户题材备注",
  sourceScriptId: "来源剧本",
  patternType: "模式类型",
  applicableGenres: "适用题材",
  applicableAudienceNeeds: "适用情绪",
  structureTemplate: "结构模板",
  whyItWorks: "有效原因",
  exampleEpisodes: "示例集数",
  storyEngine: "故事发动机",
  protagonistLoop: "主角循环",
  conflictEscalation: "冲突升级",
  emotionalLoop: "情绪循环",
  relationshipEngine: "关系发动机",
  suspenseEngine: "悬念发动机",
  payoffDesign: "兑现设计",
  episodeFunctionMap: "分集功能图",
  reusableSkeleton: "可复用骨架",
  nonTransferableSurface: "不可照搬表皮",
  sourceEvidence: "来源证据",
  addictiveDrivers: "追看驱动力",
  coolPointMechanisms: "爽点机制",
  curiosityDrivers: "好奇驱动",
  identificationPath: "代入路径",
  emotionalPayoffChain: "情绪兑现链",
  retentionHooks: "留存钩子",
  noveltySources: "新鲜感来源",
  fatigueRisks: "疲劳风险",
  whyItCanWork: "为什么可能有效",
  whyItMayFail: "为什么可能失败",
  surfacePlot: "表层剧情",
  structuralFunction: "结构功能",
  characterFunction: "人物功能",
  audiencePsychology: "观众心理",
  abstractTemplate: "抽象模板",
  variableSlots: "变量槽",
  applicableStages: "适用阶段",
  usageConstraints: "使用条件",
  antiPatterns: "反例/误用",
  transferPrompt: "迁移提示词",
  scoringRubric: "评分标准",
  patternCardIds: "Pattern Card",
  promptAdditions: "Prompt 补充",
  positiveExamples: "正例",
  negativeExamples: "反例",
  evaluationCriteria: "评估标准",
  variableMapping: "变量映射",
  newStoryEngine: "新故事发动机",
  newProtagonistLoop: "新主角循环",
  firstFiveEpisodes: "前五集",
  outlineSeed: "大纲种子",
  transferScore: "迁移分",
  copiedSurfaceRisks: "照搬表皮风险",
  mechanismCoverage: "机制覆盖",
  missingAudiencePayoff: "缺失情绪兑现",
  weakCharacterMotivation: "人物动机弱点"
};

export function labelForKey(key) {
  return fieldLabels[key] || "补充字段";
}
